
services:
  lxctest:
    build:
      context: tests/integration/
    volumes:
      - ./lxcext.conf:/root/lxcext.conf
      - ./lxcext.py:/root/lxcext.py
      - ./lxcext/:/root/lxcext/
      - ./tests/:/root/tests/
      - ./faked_storage/:/root/faked_storage/

    cap_add: ['SYS_ADMIN']
    devices:
      - /dev/fuse:/dev/fuse
      - /dev/loop0:/dev/loop0
    environment:
      LOOP_DEV: "/dev/loop0"
    security_opt:
      - apparmor=unconfined
    privileged: true
