
services:
  lxctest:
    build:
      context: .
    volumes:
      - ./src/lxcext:/usr/local/bin/lxcext
      - ./src/lxcext-create.sh:/usr/local/bin/lxcext-create.sh
      - ./src/lxcext-expand.sh:/usr/local/bin/lxcext-expand.sh
      - ./src/lxcext-mount.sh:/usr/local/bin/lxcext-mount.sh

      # create "test block device"
      # dd if=/dev/zero of=./8g.iso bs=1048576 count=8192
      - ./testdata/8g.iso:/mnt/8g.iso

    cap_add: ['SYS_ADMIN']
    privileged: true
