#!/bin/bash

if [ -n "$PRETEND" ] && [[ $(echo "$PRETEND" | tr '[:upper:]' '[:lower:]') =~ ^y|yes|1|on$ ]]; then
  RUN="echo [pretend] "
else
  RUN=
fi

[ -n "$DEBUG" ] && [[ $(echo "$DEBUG" | tr '[:upper:]' '[:lower:]') =~ ^y|yes|1|on$ ]] && \
        set -xe || set -e


if [ -z $VGNAME ] ; then
  VGNAME="vga"
fi

LXC_CONT_NAME_RE=^[0-9a-zA-Z_\-\.]+$

BASE_SCRIPT="$(basename "$0")"
script_dir="$(dirname "$0")"

for script in $(ls $script_dir/$BASE_SCRIPT-*.sh); do
  if [ -x $script ]; then
    source $script
  fi
done


function print_help() {
  cat << EOF
$BASE_SCRIPT ls
      ls - list LXC containers
EOF
  mnt_print_help
  exp_print_help
  cra_print_help
}

function op_ls() {
  lxc-ls -f
}

if [ -n "$1" ] && [[ "$1" =~ ^[a-zA-Z0-9]{1,128}$ ]] ;  then
  op_fun=op_$1

  if ! declare -F "$op_fun" > /dev/null; then
    echo "Undefined operation: $1"
    exit 1
  fi

  $op_fun $2 $3 $4
else
  print_help
fi

exit 0
